#!/bin/bash

ARCHS=(
    linux/386
    linux/amd64
    linux/arm/v6
    linux/arm/v7
    linux/arm64
    linux/ppc64le
    linux/riscv64
    linux/s390x
)

for ARCH in ${ARCHS[@]}; do
    docker build --platform $ARCH -f $DOCKERFILE_PATH -t $IMAGE_NAME .
done